BEGIN;

DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS buyer;
DROP TABLE IF EXISTS seller_products;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS seller;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS service_type_enum;
DROP TYPE IF EXISTS user_type_enum;

CREATE TYPE user_type_enum AS ENUM(
    'seller',
    'buyer'
);

CREATE TABLE users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    avatar_url TEXT DEFAULT 'default' NOT NULL,
    user_type user_type_enum NOT NULL
);

CREATE TYPE service_type_enum AS ENUM(
    'food and drinks',
    'clothing and accessories',
    'home and party decor',
    'educational',
    'body healing',
    'tattoo and piercing'
);

CREATE TABLE seller(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login_id INTEGER REFERENCES users(id) NOT NULL UNIQUE,
    shop_name TEXT NOT NULL,
    address TEXT NOT NULL,
    description TEXT, 
    start_date DATE DEFAULT NOW(),
    end_date DATE DEFAULT NOW(),
    opening_time TIME DEFAULT '00:00:00',
    closing_time TIME DEFAULT '00:00:00',
    service_type service_type_enum NOT NULL 
);

CREATE TABLE products(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item TEXT NOT NULL,
    price NUMERIC(9,2) DEFAULT 0.0,
    description TEXT NOT NUll,
    image_url TEXT DEFAULT 'no_url' NOT NULL
);

CREATE TABLE seller_products(
    seller_id INTEGER REFERENCES seller(id) NOT NULL,
    product_id INTEGER REFERENCES products(id) NOT NULL,
    PRIMARY KEY (seller_id, product_id)
);

CREATE TABLE buyer(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login_id INTEGER REFERENCES users(id) NOT NULL UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE reviews(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review TEXT NOT NULL,
    rating NUMERIC(3,2) NOT NUll,
    seller_id INTEGER REFERENCES seller(id) NOT NULL,
    buyer_id INTEGER REFERENCES buyer(id) NOT NULL
);

INSERT INTO users (username, password, user_type) VALUES 
    ('dummyseller001', 'password', 'seller'),
    ('dummybuyer002', 'password', 'buyer'),
    ('ramanaujla', 'password', 'seller');

INSERT INTO seller(login_id, shop_name, address, start_date, end_date, opening_time, closing_time, service_type, description) VALUES
    (1, 'Dummy Shop', '1234 ABC Street, New York, NY 11020', '2019-12-24', '2019-12-31',  '10:00:00', '22:00:00', 'food and drinks', 'Selling food and drinks'),
    (3, 'Come Code with Us', '7133 Foxthorn Dr, Canton, MI 48187', '2019-12-31', '2020-01-31', '08:00:00', '14:00:00', 'educational', 'Helping students learn new tech stack');


INSERT INTO buyer(login_id, name) VALUES
    (2, 'Dummy Buyer');

INSERT INTO products (item, price, description) VALUES
    ('Classic Grilled Cheese Sandwich', 10.00, 'cheddar and white American cheese pressed on brioche bread'),
    ('Cali Chicken Club', 9.99, 'bacon, smashed avocado, tomatoes, romaine, mozzarella & basil garlic mayo' ),
    ('Blue Hooded Casual Graphic Pullovers', 18.86, 'ROMWE Blue Hooded Casual Graphic Pullovers Fabric has some stretchLong Sleeve Spring/Fall Regular Fit Drawstring Men Sweatshirts, size features are:,Length: Regular ,Sleeve Length:Long Sleeve'),
    ('React Coding', 0.00, 'Open Source Coding Challenges'),
    ('Java Programming', 10.00, 'Practice and Solve advanced programming solutions');

INSERT INTO seller_products (seller_id, product_id) VALUES
    (1,1),
    (1,2),
    (2,4),
    (2,5);

COMMIT;