BEGIN;

CREATE TYPE user_type_enum AS ENUM(
    'seller',
    'buyer'
);

CREATE TABLE users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    user_type user_type_enum NOT NULL
);

COMMIT;